services:
  foreteternelledataapi-docs:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./docs/api/openapi.yml:/api/openapi.yml
    environment:
      SWAGGER_JSON: /api/openapi.yml

