// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package pkmnapispec




type PokemonScroll struct {

	Content []PokemonThumbnail `json:"content"`

	// True if there are elements left to fetch
	HasMore bool `json:"hasMore"`
}

// AssertPokemonScrollRequired checks if the required fields are not zero-ed
func AssertPokemonScrollRequired(obj PokemonScroll) error {
	elements := map[string]interface{}{
		"content": obj.Content,
		"hasMore": obj.HasMore,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Content {
		if err := AssertPokemonThumbnailRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertPokemonScrollConstraints checks if the values respects the defined constraints
func AssertPokemonScrollConstraints(obj PokemonScroll) error {
	for _, el := range obj.Content {
		if err := AssertPokemonThumbnailConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
