// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package pkmnapispec




// TypePartial - An object containing partial data of a pokemon type
type TypePartial struct {

	// The translated name of the pokemon type
	Name string `json:"name"`

	// The symbol of the pokemon type
	Symbol string `json:"symbol"`

	// The color of the pokemon type
	Color string `json:"color"`
}

// AssertTypePartialRequired checks if the required fields are not zero-ed
func AssertTypePartialRequired(obj TypePartial) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"symbol": obj.Symbol,
		"color": obj.Color,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTypePartialConstraints checks if the values respects the defined constraints
func AssertTypePartialConstraints(obj TypePartial) error {
	return nil
}
