// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package pkmnapispec




// Scroll - A list of content
type Scroll struct {

	// Contains the items of the list
	Content []string `json:"content,omitempty"`

	// True if there are elements left to fetch
	HasMore bool `json:"hasMore,omitempty"`
}

// AssertScrollRequired checks if the required fields are not zero-ed
func AssertScrollRequired(obj Scroll) error {
	return nil
}

// AssertScrollConstraints checks if the values respects the defined constraints
func AssertScrollConstraints(obj Scroll) error {
	return nil
}
