// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package pkmnapispec




// PokemonDetails - An object containing detailed data of a pokemon with its main form
type PokemonDetails struct {

	// The symbol of the pokemon
	Symbol string `json:"symbol"`

	// The number of the pokemon
	Number int32 `json:"number"`

	Form FormDetails `json:"form"`
}

// AssertPokemonDetailsRequired checks if the required fields are not zero-ed
func AssertPokemonDetailsRequired(obj PokemonDetails) error {
	elements := map[string]interface{}{
		"symbol": obj.Symbol,
		"number": obj.Number,
		"form": obj.Form,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertFormDetailsRequired(obj.Form); err != nil {
		return err
	}
	return nil
}

// AssertPokemonDetailsConstraints checks if the values respects the defined constraints
func AssertPokemonDetailsConstraints(obj PokemonDetails) error {
	if err := AssertFormDetailsConstraints(obj.Form); err != nil {
		return err
	}
	return nil
}
