// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package pkmnapispec




// TypeDetails - An object containing detailed data of a pokemon type
type TypeDetails struct {

	// The translated name of the pokemon type
	Name string `json:"name"`

	// The symbol of the pokemon type
	Symbol string `json:"symbol"`

	// The color of the pokemon type
	Color string `json:"color"`

	// The damage inflicted by this type
	TypeDamage map[string]float32 `json:"typeDamage"`
}

// AssertTypeDetailsRequired checks if the required fields are not zero-ed
func AssertTypeDetailsRequired(obj TypeDetails) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"symbol": obj.Symbol,
		"color": obj.Color,
		"typeDamage": obj.TypeDamage,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertTypeDetailsConstraints checks if the values respects the defined constraints
func AssertTypeDetailsConstraints(obj TypeDetails) error {
	return nil
}
