// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package pkmnapispec




// FormPartial - An object containing the data of a pokemon form (ev, iv, ...)
type FormPartial struct {

	// The form number
	Number int32 `json:"number"`

	// The translated name of the form
	Name string `json:"name"`

	Type1 *TypePartial `json:"type1"`

	Type2 *TypePartial `json:"type2,omitempty"`

	// The base HP stat
	BaseHp int32 `json:"baseHp"`

	// The base attack stat
	BaseAtk int32 `json:"baseAtk"`

	// The base defense stat
	BaseDfe int32 `json:"baseDfe"`

	// The base speed stat
	BaseSpd int32 `json:"baseSpd"`

	// The base special attack stat
	BaseAts int32 `json:"baseAts"`

	// The base special defense stat
	BaseDfs int32 `json:"baseDfs"`
}

// AssertFormPartialRequired checks if the required fields are not zero-ed
func AssertFormPartialRequired(obj FormPartial) error {
	elements := map[string]interface{}{
		"number": obj.Number,
		"name": obj.Name,
		"type1": obj.Type1,
		"baseHp": obj.BaseHp,
		"baseAtk": obj.BaseAtk,
		"baseDfe": obj.BaseDfe,
		"baseSpd": obj.BaseSpd,
		"baseAts": obj.BaseAts,
		"baseDfs": obj.BaseDfs,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if obj.Type1 != nil {
		if err := AssertTypePartialRequired(*obj.Type1); err != nil {
			return err
		}
	}
	if obj.Type2 != nil {
		if err := AssertTypePartialRequired(*obj.Type2); err != nil {
			return err
		}
	}
	return nil
}

// AssertFormPartialConstraints checks if the values respects the defined constraints
func AssertFormPartialConstraints(obj FormPartial) error {
    if obj.Type1 != nil {
     	if err := AssertTypePartialConstraints(*obj.Type1); err != nil {
     		return err
     	}
    }
    if obj.Type2 != nil {
     	if err := AssertTypePartialConstraints(*obj.Type2); err != nil {
     		return err
     	}
    }
	return nil
}
