// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package pkmnapispec




// Scroll - A list of content
type Scroll struct {

	// Contains the items of the list
	Content []string `json:"content"`

	// True if there are elements left to fetch
	HasMore bool `json:"hasMore"`
}

// AssertScrollRequired checks if the required fields are not zero-ed
func AssertScrollRequired(obj Scroll) error {
	elements := map[string]interface{}{
		"content": obj.Content,
		"hasMore": obj.HasMore,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertScrollConstraints checks if the values respects the defined constraints
func AssertScrollConstraints(obj Scroll) error {
	return nil
}
