// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package pkmnapispec




// PokemonThumbnail - An object containing base information to display a pokemon
type PokemonThumbnail struct {

	// The symbol of the pokemon
	Symbol string `json:"symbol"`

	// The translated name of the first pokemon's form
	Name string `json:"name"`

	// The number of the pokemon
	Number int32 `json:"number"`

	// The form of the pokemon
	Form int32 `json:"form"`

	// The image symbol of the pokemon
	Image string `json:"image"`

	Type1 *TypePartial `json:"type1"`

	Type2 *TypePartial `json:"type2,omitempty"`

	// Custom properties setted by the developer
	CustomProperties map[string]interface{} `json:"customProperties,omitempty"`
}

// AssertPokemonThumbnailRequired checks if the required fields are not zero-ed
func AssertPokemonThumbnailRequired(obj PokemonThumbnail) error {
	elements := map[string]interface{}{
		"symbol": obj.Symbol,
		"name": obj.Name,
		"number": obj.Number,
		"form": obj.Form,
		"image": obj.Image,
		"type1": obj.Type1,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if obj.Type1 != nil {
		if err := AssertTypePartialRequired(*obj.Type1); err != nil {
			return err
		}
	}
	if obj.Type2 != nil {
		if err := AssertTypePartialRequired(*obj.Type2); err != nil {
			return err
		}
	}
	return nil
}

// AssertPokemonThumbnailConstraints checks if the values respects the defined constraints
func AssertPokemonThumbnailConstraints(obj PokemonThumbnail) error {
    if obj.Type1 != nil {
     	if err := AssertTypePartialConstraints(*obj.Type1); err != nil {
     		return err
     	}
    }
    if obj.Type2 != nil {
     	if err := AssertTypePartialConstraints(*obj.Type2); err != nil {
     		return err
     	}
    }
	return nil
}
