// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package studioapi

import (
	"net/http"
	"strings"

	"github.com/ForetEternelle/PokemonStudioDataApi/pkg/studio"
	"github.com/go-chi/chi/v5"
)

// AbilitiesAPIController binds http requests to an api service and writes the service results to the http response
type AbilitiesAPIController struct {
	service      AbilitiesAPIServicer
	errorHandler ErrorHandler
}

// AbilitiesAPIOption for how the controller is set up.
type AbilitiesAPIOption func(*AbilitiesAPIController)

// WithAbilitiesAPIErrorHandler inject ErrorHandler into controller
func WithAbilitiesAPIErrorHandler(h ErrorHandler) AbilitiesAPIOption {
	return func(c *AbilitiesAPIController) {
		c.errorHandler = h
	}
}

// NewAbilitiesAPIController creates a default api controller
func NewAbilitiesAPIController(s AbilitiesAPIServicer, opts ...AbilitiesAPIOption) *AbilitiesAPIController {
	controller := &AbilitiesAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the AbilitiesAPIController
func (c *AbilitiesAPIController) Routes() Routes {
	return Routes{
		"GetAbilities": Route{
			strings.ToUpper("Get"),
			"/api/abilities",
			c.GetAbilities,
		},
		"GetAbilityDetails": Route{
			strings.ToUpper("Get"),
			"/api/abilities/{symbol}",
			c.GetAbilityDetails,
		},
	}
}

// GetAbilities - Get all abilities
func (c *AbilitiesAPIController) GetAbilities(w http.ResponseWriter, r *http.Request) {
	acceptLanguageParam := r.Header.Get("Accept-Language")
	acceptLang := studio.ParseAcceptLanguageParam(acceptLanguageParam)
	result, err := c.service.GetAbilities(r.Context(), acceptLang)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetAbilityDetails - Get an ability details
func (c *AbilitiesAPIController) GetAbilityDetails(w http.ResponseWriter, r *http.Request) {
	symbolParam := chi.URLParam(r, "symbol")
	if symbolParam == "" {
		c.errorHandler(w, r, &RequiredError{"symbol"}, nil)
		return
	}
	acceptLanguageParam := r.Header.Get("Accept-Language")
	acceptLang := studio.ParseAcceptLanguageParam(acceptLanguageParam)
	result, err := c.service.GetAbilityDetails(r.Context(), symbolParam, acceptLang)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
