// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package studioapi

import (
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"
)

// MovesAPIController binds http requests to an api service and writes the service results to the http response
type MovesAPIController struct {
	service MovesAPIServicer
	errorHandler ErrorHandler
}

// MovesAPIOption for how the controller is set up.
type MovesAPIOption func(*MovesAPIController)

// WithMovesAPIErrorHandler inject ErrorHandler into controller
func WithMovesAPIErrorHandler(h ErrorHandler) MovesAPIOption {
	return func(c *MovesAPIController) {
		c.errorHandler = h
	}
}

// NewMovesAPIController creates a default api controller
func NewMovesAPIController(s MovesAPIServicer, opts ...MovesAPIOption) *MovesAPIController {
	controller := &MovesAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the MovesAPIController
func (c *MovesAPIController) Routes() Routes {
	return Routes{
		"GetMove": Route{
			strings.ToUpper("Get"),
			"/moves/{symbol}",
			c.GetMove,
		},
		"GetMoveDetails": Route{
			strings.ToUpper("Get"),
			"/moves/detail/{symbol}",
			c.GetMoveDetails,
		},
	}
}

// GetMove - Get a move with it most important details
func (c *MovesAPIController) GetMove(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	symbolParam := chi.URLParam(r, "symbol")
	if symbolParam == "" {
		c.errorHandler(w, r, &RequiredError{"symbol"}, nil)
		return
	}
	var langParam string
	if query.Has("lang") {
		param := query.Get("lang")

		langParam = param
	} else {
		param := "en"
		langParam = param
	}
	result, err := c.service.GetMove(r.Context(), symbolParam, langParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetMoveDetails - Get a move details
func (c *MovesAPIController) GetMoveDetails(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	symbolParam := chi.URLParam(r, "symbol")
	if symbolParam == "" {
		c.errorHandler(w, r, &RequiredError{"symbol"}, nil)
		return
	}
	var langParam string
	if query.Has("lang") {
		param := query.Get("lang")

		langParam = param
	} else {
		param := "en"
		langParam = param
	}
	result, err := c.service.GetMoveDetails(r.Context(), symbolParam, langParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
