// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package studioapi

// MoveDetails - Full definition of a battle move
type MoveDetails struct {

	// The translated name of the move
	Name string `json:"name,omitempty"`

	// The translated description of the move
	Description string `json:"description,omitempty"`

	// The symbol of the move
	Symbol string `json:"symbol,omitempty"`

	Type *TypePartial `json:"type,omitempty"`

	// The category of the move
	Category string `json:"category,omitempty"`

	// The power of the move
	Power int32 `json:"power,omitempty"`

	// The accuracy of the move
	Accuracy int32 `json:"accuracy,omitempty"`

	// The PP of the move
	Pp int32 `json:"pp,omitempty"`

	// The critical hit rate of the move
	CriticalRate int32 `json:"criticalRate,omitempty"`

	// The priority of the move
	Priority int32 `json:"priority,omitempty"`

	Targeting map[string]interface{} `json:"targeting,omitempty"`

	Execution map[string]interface{} `json:"execution,omitempty"`

	MechanicalTags []map[string]interface{} `json:"mechanicalTags,omitempty"`

	Interactions map[string]interface{} `json:"interactions,omitempty"`

	SecondaryEffects map[string]interface{} `json:"secondaryEffects,omitempty"`
}

// AssertMoveDetailsRequired checks if the required fields are not zero-ed
func AssertMoveDetailsRequired(obj MoveDetails) error {
	if obj.Type != nil {
		if err := AssertTypePartialRequired(*obj.Type); err != nil {
			return err
		}
	}
	return nil
}

// AssertMoveDetailsConstraints checks if the values respects the defined constraints
func AssertMoveDetailsConstraints(obj MoveDetails) error {
	if obj.Type != nil {
		if err := AssertTypePartialConstraints(*obj.Type); err != nil {
			return err
		}
	}
	return nil
}
