// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package studioapi




// PokemonThumbnail - An object containing base information to display a pokemon
type PokemonThumbnail struct {

	// The symbol of the pokemon
	Symbol string `json:"symbol,omitempty"`

	// The translated name of the first pokemon's form
	Name string `json:"name,omitempty"`

	// The number of the pokemon
	Number int32 `json:"number,omitempty"`

	// The image symbol of the pokemon
	Image string `json:"image,omitempty"`

	Type1 *TypePartial `json:"type1,omitempty"`

	Type2 *TypePartial `json:"type2,omitempty"`

	// Custom properties setted by the developer
	CustomProperties map[string]interface{} `json:"customProperties,omitempty"`
}

// AssertPokemonThumbnailRequired checks if the required fields are not zero-ed
func AssertPokemonThumbnailRequired(obj PokemonThumbnail) error {
	if obj.Type1 != nil {
		if err := AssertTypePartialRequired(*obj.Type1); err != nil {
			return err
		}
	}
	if obj.Type2 != nil {
		if err := AssertTypePartialRequired(*obj.Type2); err != nil {
			return err
		}
	}
	return nil
}

// AssertPokemonThumbnailConstraints checks if the values respects the defined constraints
func AssertPokemonThumbnailConstraints(obj PokemonThumbnail) error {
    if obj.Type1 != nil {
     	if err := AssertTypePartialConstraints(*obj.Type1); err != nil {
     		return err
     	}
    }
    if obj.Type2 != nil {
     	if err := AssertTypePartialConstraints(*obj.Type2); err != nil {
     		return err
     	}
    }
	return nil
}
