// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package studioapi

// MovePartial - An object containing partial data of a pokemon move
type MovePartial struct {

	// The symbol of the pokemon move
	Symbol string `json:"symbol,omitempty"`

	// The translated name of the pokemon move
	Name string `json:"name,omitempty"`

	Type *TypePartial `json:"type,omitempty"`

	// The category of the pokemon move
	Category string `json:"category,omitempty"`

	// The PP of the pokemon move
	Pp int32 `json:"pp,omitempty"`

	// The power of the pokemon move
	Power int32 `json:"power,omitempty"`

	// The accuracy of the pokemon move
	Accuracy int32 `json:"accuracy,omitempty"`
}

// AssertMovePartialRequired checks if the required fields are not zero-ed
func AssertMovePartialRequired(obj MovePartial) error {
	if obj.Type != nil {
		if err := AssertTypePartialRequired(*obj.Type); err != nil {
			return err
		}
	}
	return nil
}

// AssertMovePartialConstraints checks if the values respects the defined constraints
func AssertMovePartialConstraints(obj MovePartial) error {
	if obj.Type != nil {
		if err := AssertTypePartialConstraints(*obj.Type); err != nil {
			return err
		}
	}
	return nil
}
