// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package studioapi




// FormPartial - An object containing the data of a pokemon form (ev, iv, ...)
type FormPartial struct {

	// The form number
	Form *int32 `json:"form,omitempty"`

	// The translated name of the form
	Name string `json:"name,omitempty"`

	Type1 *TypePartial `json:"type1,omitempty"`

	Type2 *TypePartial `json:"type2,omitempty"`

	// The base HP stat
	BaseHp int32 `json:"baseHp,omitempty"`

	// The base attack stat
	BaseAtk int32 `json:"baseAtk,omitempty"`

	// The base defense stat
	BaseDfe int32 `json:"baseDfe,omitempty"`

	// The base speed stat
	BaseSpd int32 `json:"baseSpd,omitempty"`

	// The base special attack stat
	BaseAts int32 `json:"baseAts,omitempty"`

	// The base special defense stat
	BaseDfs int32 `json:"baseDfs,omitempty"`

	// The image symbol of the form
	Image string `json:"image,omitempty"`
}

// AssertFormPartialRequired checks if the required fields are not zero-ed
func AssertFormPartialRequired(obj FormPartial) error {
	if obj.Type1 != nil {
		if err := AssertTypePartialRequired(*obj.Type1); err != nil {
			return err
		}
	}
	if obj.Type2 != nil {
		if err := AssertTypePartialRequired(*obj.Type2); err != nil {
			return err
		}
	}
	return nil
}

// AssertFormPartialConstraints checks if the values respects the defined constraints
func AssertFormPartialConstraints(obj FormPartial) error {
    if obj.Type1 != nil {
     	if err := AssertTypePartialConstraints(*obj.Type1); err != nil {
     		return err
     	}
    }
    if obj.Type2 != nil {
     	if err := AssertTypePartialConstraints(*obj.Type2); err != nil {
     		return err
     	}
    }
	return nil
}
