// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Pokemon Studio API
 *
 * API for the Pokemon Studio
 *
 * API version: 0.0.1
 */

package studioapi




// AbilityDetails - An object containing detailed data of a pokemon ability
type AbilityDetails struct {

	// The symbol of the pokemon ability
	Symbol string `json:"symbol,omitempty"`

	// The translated name of the pokemon ability
	Name string `json:"name,omitempty"`

	// The translated description of the pokemon ability
	Description string `json:"description,omitempty"`
}

// AssertAbilityDetailsRequired checks if the required fields are not zero-ed
func AssertAbilityDetailsRequired(obj AbilityDetails) error {
	return nil
}

// AssertAbilityDetailsConstraints checks if the values respects the defined constraints
func AssertAbilityDetailsConstraints(obj AbilityDetails) error {
	return nil
}
